[package]
name = "prometheus"
version = "0.8.0"
license = "Apache-2.0"
keywords = ["prometheus", "metrics"]
authors = ["overvenus@gmail.com", "siddontang@gmail.com", "vistaswx@gmail.com"]
description = "Prometheus instrumentation library for Rust applications."
readme = "README.md"
repository = "https://github.com/pingcap/rust-prometheus"
homepage = "https://github.com/pingcap/rust-prometheus"
documentation = "https://docs.rs/prometheus"
edition = "2018"

[badges]
travis-ci = { repository = "pingcap/rust-prometheus" }

[package.metadata.docs.rs]
features = ["nightly"]

[features]
default = ["protobuf"]
nightly = ["libc"]
push = ["reqwest", "libc", "protobuf"]
process = ["libc", "procfs"]
gen = ["protobuf-codegen-pure"]

[dependencies]
coarsetime = "0.1"
protobuf = { version = "2.0", optional = true }
thiserror = "1.0"
fnv = "1.0"
lazy_static = "1.3"
libc = { version = "0.2", optional = true }
cfg-if = "0.1"
spin = "0.5.2"
reqwest = { version = "0.9.5", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
procfs = { version = "0.7", optional = true, default-features = false }

[dev-dependencies]
getopts = "0.2"
hyper = "0.12"

[build-dependencies]
protobuf-codegen-pure = { version = "2.0", optional = true }

[workspace]
members = [
    "static-metric",
    "static-metric/proc-macros",
]
